version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: sh -c "pnpm exec prisma migrate deploy && pnpm run start:prod"
    env_file:
      - .env

  db:
    image: postgres:17-alpine
    container_name: db
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
